name: Deploy Move packages to github packages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]
  pull_request:
    branches: [ master ]

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          registry-url: https://npm.pkg.github.com/
      - name: Install dependencies
        run: npm ci
      # - name: Install Aptos Cli
      #   run: |
      #     curl -fsSL "https://aptos.dev/scripts/install_cli.sh" | sh
      #     aptos --version
      - name: Setup Aptos CLI
        uses: WGB5445/aptos-cli-setup@v1
        with:
          version: "7.5.0"
      - name: Build Move Packages
        run: aptos move build --included-artifacts none --save-metadata
      - name: SyncPackageJson
        run: npx ts-node ghscripts/sync_package_json.ts
      - name: Publish Move Packages
        run: npx ts-node ghscripts/publish_package.ts
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
